package com.luisbarrichello.api.ecommerce.model.category;

public enum Category {
    ALIMENTOS_E_BEBIDAS,
    MODA,
    ELETRONICOS,
    BELEZA_E_CUIDADOS_PESSOAIS,
    CASA_E_COZINHA,
    ESPORTES_E_LAZER,
    LIVROS,
    BRINQUEDOS_E_JOGOS,
    FERRAMENTAS_E_JARDIM,
    AUTOMOTIVO,
    INFORMATICA,
    SAUDE_E_BEM_ESTAR,
    MOVEIS,
    DECORACAO,
    PETS,
    VIAGEM,
    JARDINAGEM,
    ARTIGOS_DE_FESTA,
    INSTRUMENTOS_MUSICAIS,
    ARTESANATO,
    }
