
    create table address (
        is_primary boolean,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint,
        city varchar(255),
        complement varchar(255),
        country varchar(255),
        house_number varchar(255),
        neighborhood varchar(255),
        postal_code varchar(255),
        state varchar(255),
        street varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table cart_item (
        price numeric(38,2),
        quantity integer,
        id bigint generated by default as identity,
        product_id bigint,
        shopping_cart_id bigint,
        primary key (id)
    );

    create table discounts (
        discount_amount numeric(38,2),
        id bigint generated by default as identity,
        discount_code varchar(255),
        primary key (id)
    );

    create table order_items (
        price_at_purchase numeric(38,2),
        quantity integer,
        id bigint generated by default as identity,
        order_id bigint not null,
        product_id bigint not null,
        product_name varchar(255),
        primary key (id)
    );

    create table orders (
        freight_price numeric(38,2),
        price_total numeric(38,2) not null,
        taxes numeric(38,2),
        created_at timestamp(6),
        date_of_receipt timestamp(6),
        delivery_date timestamp(6),
        discount_id bigint,
        dispatch_date timestamp(6),
        id bigint generated by default as identity,
        payment_method bigint,
        return_deadline timestamp(6),
        user_id bigint,
        status varchar(255) check (status in ('IN_PREPARATION','CANCELED','PENDING_PAYMENT','DELIVERED')),
        tracking_code varchar(255) unique,
        primary key (id)
    );

    create table payment_methods (
        id bigint generated by default as identity,
        method varchar(255) not null unique,
        primary key (id)
    );

    create table products (
        dimensions float(53) not null,
        price numeric(38,2),
        sales_count integer,
        stock integer not null,
        weight float(53) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        brand varchar(255),
        category varchar(255) check (category in ('ALIMENTOS_E_BEBIDAS','MODA','ELETRONICOS','BELEZA_E_CUIDADOS_PESSOAIS','CASA_E_COZINHA','ESPORTES_E_LAZER','LIVROS','BRINQUEDOS_E_JOGOS','FERRAMENTAS_E_JARDIM','AUTOMOTIVO','INFORMATICA','SAUDE_E_BEM_ESTAR','MOVEIS','DECORACAO','PETS','VIAGEM','JARDINAGEM','ARTIGOS_DE_FESTA','INSTRUMENTOS_MUSICAIS','ARTESANATO')),
        description varchar(255),
        img_url varchar(255),
        name varchar(255),
        sku varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table shopping_cart (
        price_total_final numeric(38,2),
        price_total_items numeric(38,2),
        shipping numeric(38,2),
        taxes numeric(38,2),
        created_at timestamp(6),
        discount_id bigint,
        id bigint generated by default as identity,
        payment_method bigint,
        updated_at timestamp(6),
        user_id bigint unique,
        status varchar(255) check (status in ('ACTIVE','COMPLETED','CANCELED','PENDING_PAYMENT','SHIPPED','DELIVERED')),
        primary key (id)
    );

    create table users (
        email_verified boolean,
        is_active boolean,
        create_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_login timestamp(6),
        role_id bigint not null,
        shopping_cart_id bigint unique,
        update_at timestamp(6) not null,
        phone_number varchar(11),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password varchar(255) not null,
        reset_password_token varchar(255),
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists address 
       add constraint FK6i66ijb8twgcqtetl8eeeed6v 
       foreign key (user_id) 
       references users;

    alter table if exists cart_item 
       add constraint FKqkqmvkmbtiaqn2nfqf25ymfs2 
       foreign key (product_id) 
       references products;

    alter table if exists cart_item 
       add constraint FKe89gjdx91fxnmkkssyoim8xfu 
       foreign key (shopping_cart_id) 
       references shopping_cart;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FKsxfvku34v9ujavmj9ao69vo8s 
       foreign key (discount_id) 
       references discounts;

    alter table if exists orders 
       add constraint FK4q9i5ocee718mqyc415foi9ct 
       foreign key (payment_method) 
       references payment_methods;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists shopping_cart 
       add constraint FKdu1q2dc4vr5xbht7qxkaxdxsq 
       foreign key (discount_id) 
       references discounts;

    alter table if exists shopping_cart 
       add constraint FK5v7hqn19tbj0k6li11onu50na 
       foreign key (payment_method) 
       references payment_methods;

    alter table if exists shopping_cart 
       add constraint FKr1irjigmqcpfrvggavnr7vjyv 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    alter table if exists users 
       add constraint FKg9bdq6h4q87ner8a59wsiq39d 
       foreign key (shopping_cart_id) 
       references shopping_cart;

    create table address (
        is_primary boolean,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint,
        city varchar(255),
        complement varchar(255),
        country varchar(255),
        house_number varchar(255),
        neighborhood varchar(255),
        postal_code varchar(255),
        state varchar(255),
        street varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table cart_item (
        price numeric(38,2),
        quantity integer,
        id bigint generated by default as identity,
        product_id bigint,
        shopping_cart_id bigint,
        primary key (id)
    );

    create table discounts (
        discount_amount numeric(38,2),
        id bigint generated by default as identity,
        discount_code varchar(255),
        primary key (id)
    );

    create table order_items (
        price_at_purchase numeric(38,2),
        quantity integer,
        id bigint generated by default as identity,
        order_id bigint not null,
        product_id bigint not null,
        product_name varchar(255),
        primary key (id)
    );

    create table orders (
        freight_price numeric(38,2),
        price_total numeric(38,2) not null,
        taxes numeric(38,2),
        created_at timestamp(6),
        date_of_receipt timestamp(6),
        delivery_date timestamp(6),
        discount_id bigint,
        dispatch_date timestamp(6),
        id bigint generated by default as identity,
        payment_method bigint,
        return_deadline timestamp(6),
        user_id bigint,
        status varchar(255) check (status in ('IN_PREPARATION','CANCELED','PENDING_PAYMENT','DELIVERED')),
        tracking_code varchar(255) unique,
        primary key (id)
    );

    create table payment_methods (
        id bigint generated by default as identity,
        method varchar(255) not null unique,
        primary key (id)
    );

    create table products (
        dimensions float(53) not null,
        price numeric(38,2),
        sales_count integer,
        stock integer not null,
        weight float(53) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        brand varchar(255),
        category varchar(255) check (category in ('ALIMENTOS_E_BEBIDAS','MODA','ELETRONICOS','BELEZA_E_CUIDADOS_PESSOAIS','CASA_E_COZINHA','ESPORTES_E_LAZER','LIVROS','BRINQUEDOS_E_JOGOS','FERRAMENTAS_E_JARDIM','AUTOMOTIVO','INFORMATICA','SAUDE_E_BEM_ESTAR','MOVEIS','DECORACAO','PETS','VIAGEM','JARDINAGEM','ARTIGOS_DE_FESTA','INSTRUMENTOS_MUSICAIS','ARTESANATO')),
        description varchar(255),
        img_url varchar(255),
        name varchar(255),
        sku varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table shopping_cart (
        price_total_final numeric(38,2),
        price_total_items numeric(38,2),
        shipping numeric(38,2),
        taxes numeric(38,2),
        created_at timestamp(6),
        discount_id bigint,
        id bigint generated by default as identity,
        payment_method bigint,
        updated_at timestamp(6),
        user_id bigint unique,
        status varchar(255) check (status in ('ACTIVE','COMPLETED','CANCELED','PENDING_PAYMENT','SHIPPED','DELIVERED')),
        primary key (id)
    );

    create table users (
        email_verified boolean,
        is_active boolean,
        create_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_login timestamp(6),
        role_id bigint not null,
        shopping_cart_id bigint unique,
        update_at timestamp(6) not null,
        phone_number varchar(11),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password varchar(255) not null,
        reset_password_token varchar(255),
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists address 
       add constraint FK6i66ijb8twgcqtetl8eeeed6v 
       foreign key (user_id) 
       references users;

    alter table if exists cart_item 
       add constraint FKqkqmvkmbtiaqn2nfqf25ymfs2 
       foreign key (product_id) 
       references products;

    alter table if exists cart_item 
       add constraint FKe89gjdx91fxnmkkssyoim8xfu 
       foreign key (shopping_cart_id) 
       references shopping_cart;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FKsxfvku34v9ujavmj9ao69vo8s 
       foreign key (discount_id) 
       references discounts;

    alter table if exists orders 
       add constraint FK4q9i5ocee718mqyc415foi9ct 
       foreign key (payment_method) 
       references payment_methods;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists shopping_cart 
       add constraint FKdu1q2dc4vr5xbht7qxkaxdxsq 
       foreign key (discount_id) 
       references discounts;

    alter table if exists shopping_cart 
       add constraint FK5v7hqn19tbj0k6li11onu50na 
       foreign key (payment_method) 
       references payment_methods;

    alter table if exists shopping_cart 
       add constraint FKr1irjigmqcpfrvggavnr7vjyv 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    alter table if exists users 
       add constraint FKg9bdq6h4q87ner8a59wsiq39d 
       foreign key (shopping_cart_id) 
       references shopping_cart;

    create table address (
        is_primary boolean,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint,
        city varchar(255),
        complement varchar(255),
        country varchar(255),
        house_number varchar(255),
        neighborhood varchar(255),
        postal_code varchar(255),
        state varchar(255),
        street varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table cart_item (
        price numeric(38,2),
        quantity integer,
        id bigint generated by default as identity,
        product_id bigint,
        shopping_cart_id bigint,
        primary key (id)
    );

    create table discounts (
        discount_amount numeric(38,2),
        id bigint generated by default as identity,
        discount_code varchar(255),
        primary key (id)
    );

    create table order_items (
        price_at_purchase numeric(38,2),
        quantity integer,
        id bigint generated by default as identity,
        order_id bigint not null,
        product_id bigint not null,
        product_name varchar(255),
        primary key (id)
    );

    create table orders (
        freight_price numeric(38,2),
        price_total numeric(38,2) not null,
        taxes numeric(38,2),
        created_at timestamp(6),
        date_of_receipt timestamp(6),
        delivery_date timestamp(6),
        discount_id bigint,
        dispatch_date timestamp(6),
        id bigint generated by default as identity,
        payment_method bigint,
        return_deadline timestamp(6),
        user_id bigint,
        status varchar(255) check (status in ('IN_PREPARATION','CANCELED','PENDING_PAYMENT','DELIVERED')),
        tracking_code varchar(255) unique,
        primary key (id)
    );

    create table payment_methods (
        id bigint generated by default as identity,
        method varchar(255) not null unique,
        primary key (id)
    );

    create table products (
        dimensions float(53) not null,
        price numeric(38,2),
        sales_count integer,
        stock integer not null,
        weight float(53) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        brand varchar(255),
        category varchar(255) check (category in ('ALIMENTOS_E_BEBIDAS','MODA','ELETRONICOS','BELEZA_E_CUIDADOS_PESSOAIS','CASA_E_COZINHA','ESPORTES_E_LAZER','LIVROS','BRINQUEDOS_E_JOGOS','FERRAMENTAS_E_JARDIM','AUTOMOTIVO','INFORMATICA','SAUDE_E_BEM_ESTAR','MOVEIS','DECORACAO','PETS','VIAGEM','JARDINAGEM','ARTIGOS_DE_FESTA','INSTRUMENTOS_MUSICAIS','ARTESANATO')),
        description varchar(255),
        img_url varchar(255),
        name varchar(255),
        sku varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table shopping_cart (
        price_total_final numeric(38,2),
        price_total_items numeric(38,2),
        shipping numeric(38,2),
        taxes numeric(38,2),
        created_at timestamp(6),
        discount_id bigint,
        id bigint generated by default as identity,
        payment_method bigint,
        updated_at timestamp(6),
        user_id bigint unique,
        status varchar(255) check (status in ('ACTIVE','COMPLETED','CANCELED','PENDING_PAYMENT','SHIPPED','DELIVERED')),
        primary key (id)
    );

    create table users (
        email_verified boolean,
        is_active boolean,
        create_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_login timestamp(6),
        role_id bigint not null,
        shopping_cart_id bigint unique,
        update_at timestamp(6) not null,
        phone_number varchar(11),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password varchar(255) not null,
        reset_password_token varchar(255),
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists address 
       add constraint FK6i66ijb8twgcqtetl8eeeed6v 
       foreign key (user_id) 
       references users;

    alter table if exists cart_item 
       add constraint FKqkqmvkmbtiaqn2nfqf25ymfs2 
       foreign key (product_id) 
       references products;

    alter table if exists cart_item 
       add constraint FKe89gjdx91fxnmkkssyoim8xfu 
       foreign key (shopping_cart_id) 
       references shopping_cart;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FKsxfvku34v9ujavmj9ao69vo8s 
       foreign key (discount_id) 
       references discounts;

    alter table if exists orders 
       add constraint FK4q9i5ocee718mqyc415foi9ct 
       foreign key (payment_method) 
       references payment_methods;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists shopping_cart 
       add constraint FKdu1q2dc4vr5xbht7qxkaxdxsq 
       foreign key (discount_id) 
       references discounts;

    alter table if exists shopping_cart 
       add constraint FK5v7hqn19tbj0k6li11onu50na 
       foreign key (payment_method) 
       references payment_methods;

    alter table if exists shopping_cart 
       add constraint FKr1irjigmqcpfrvggavnr7vjyv 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    alter table if exists users 
       add constraint FKg9bdq6h4q87ner8a59wsiq39d 
       foreign key (shopping_cart_id) 
       references shopping_cart;

    create table address (
        is_primary boolean,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint,
        city varchar(255),
        complement varchar(255),
        country varchar(255),
        house_number varchar(255),
        neighborhood varchar(255),
        postal_code varchar(255),
        state varchar(255),
        street varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table cart_item (
        price numeric(38,2),
        quantity integer,
        id bigint generated by default as identity,
        product_id bigint,
        shopping_cart_id bigint,
        primary key (id)
    );

    create table discounts (
        discount_amount numeric(38,2),
        id bigint generated by default as identity,
        discount_code varchar(255),
        primary key (id)
    );

    create table order_items (
        price_at_purchase numeric(38,2),
        quantity integer,
        id bigint generated by default as identity,
        order_id bigint not null,
        product_id bigint not null,
        product_name varchar(255),
        primary key (id)
    );

    create table orders (
        freight_price numeric(38,2),
        price_total numeric(38,2) not null,
        taxes numeric(38,2),
        created_at timestamp(6),
        date_of_receipt timestamp(6),
        delivery_date timestamp(6),
        discount_id bigint,
        dispatch_date timestamp(6),
        id bigint generated by default as identity,
        payment_method bigint,
        return_deadline timestamp(6),
        user_id bigint,
        status varchar(255) check (status in ('IN_PREPARATION','CANCELED','PENDING_PAYMENT','DELIVERED')),
        tracking_code varchar(255) unique,
        primary key (id)
    );

    create table payment_methods (
        id bigint generated by default as identity,
        method varchar(255) not null unique,
        primary key (id)
    );

    create table products (
        dimensions float(53) not null,
        price numeric(38,2),
        sales_count integer,
        stock integer not null,
        weight float(53) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        brand varchar(255),
        category varchar(255) check (category in ('ALIMENTOS_E_BEBIDAS','MODA','ELETRONICOS','BELEZA_E_CUIDADOS_PESSOAIS','CASA_E_COZINHA','ESPORTES_E_LAZER','LIVROS','BRINQUEDOS_E_JOGOS','FERRAMENTAS_E_JARDIM','AUTOMOTIVO','INFORMATICA','SAUDE_E_BEM_ESTAR','MOVEIS','DECORACAO','PETS','VIAGEM','JARDINAGEM','ARTIGOS_DE_FESTA','INSTRUMENTOS_MUSICAIS','ARTESANATO')),
        description varchar(255),
        img_url varchar(255),
        name varchar(255),
        sku varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table shopping_cart (
        price_total_final numeric(38,2),
        price_total_items numeric(38,2),
        shipping numeric(38,2),
        taxes numeric(38,2),
        created_at timestamp(6),
        discount_id bigint,
        id bigint generated by default as identity,
        payment_method bigint,
        updated_at timestamp(6),
        user_id bigint unique,
        status varchar(255) check (status in ('ACTIVE','COMPLETED','CANCELED','PENDING_PAYMENT','SHIPPED','DELIVERED')),
        primary key (id)
    );

    create table users (
        email_verified boolean,
        is_active boolean,
        create_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_login timestamp(6),
        role_id bigint not null,
        shopping_cart_id bigint unique,
        update_at timestamp(6) not null,
        phone_number varchar(11),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password varchar(255) not null,
        reset_password_token varchar(255),
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists address 
       add constraint FK6i66ijb8twgcqtetl8eeeed6v 
       foreign key (user_id) 
       references users;

    alter table if exists cart_item 
       add constraint FKqkqmvkmbtiaqn2nfqf25ymfs2 
       foreign key (product_id) 
       references products;

    alter table if exists cart_item 
       add constraint FKe89gjdx91fxnmkkssyoim8xfu 
       foreign key (shopping_cart_id) 
       references shopping_cart;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FKsxfvku34v9ujavmj9ao69vo8s 
       foreign key (discount_id) 
       references discounts;

    alter table if exists orders 
       add constraint FK4q9i5ocee718mqyc415foi9ct 
       foreign key (payment_method) 
       references payment_methods;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists shopping_cart 
       add constraint FKdu1q2dc4vr5xbht7qxkaxdxsq 
       foreign key (discount_id) 
       references discounts;

    alter table if exists shopping_cart 
       add constraint FK5v7hqn19tbj0k6li11onu50na 
       foreign key (payment_method) 
       references payment_methods;

    alter table if exists shopping_cart 
       add constraint FKr1irjigmqcpfrvggavnr7vjyv 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    alter table if exists users 
       add constraint FKg9bdq6h4q87ner8a59wsiq39d 
       foreign key (shopping_cart_id) 
       references shopping_cart;

    create table address (
        is_primary boolean,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint,
        city varchar(255),
        complement varchar(255),
        country varchar(255),
        house_number varchar(255),
        neighborhood varchar(255),
        postal_code varchar(255),
        state varchar(255),
        street varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table cart_item (
        price numeric(38,2),
        quantity integer,
        id bigint generated by default as identity,
        product_id bigint,
        shopping_cart_id bigint,
        primary key (id)
    );

    create table discounts (
        discount_amount numeric(38,2),
        id bigint generated by default as identity,
        discount_code varchar(255),
        primary key (id)
    );

    create table order_items (
        price_at_purchase numeric(38,2),
        quantity integer,
        id bigint generated by default as identity,
        order_id bigint not null,
        product_id bigint not null,
        product_name varchar(255),
        primary key (id)
    );

    create table orders (
        freight_price numeric(38,2),
        price_total numeric(38,2) not null,
        taxes numeric(38,2),
        created_at timestamp(6),
        date_of_receipt timestamp(6),
        delivery_date timestamp(6),
        discount_id bigint,
        dispatch_date timestamp(6),
        id bigint generated by default as identity,
        payment_method bigint,
        return_deadline timestamp(6),
        user_id bigint,
        status varchar(255) check (status in ('IN_PREPARATION','CANCELED','PENDING_PAYMENT','DELIVERED')),
        tracking_code varchar(255) unique,
        primary key (id)
    );

    create table payment_methods (
        id bigint generated by default as identity,
        method varchar(255) not null unique,
        primary key (id)
    );

    create table products (
        dimensions float(53) not null,
        price numeric(38,2),
        sales_count integer,
        stock integer not null,
        weight float(53) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        brand varchar(255),
        category varchar(255) check (category in ('ALIMENTOS_E_BEBIDAS','MODA','ELETRONICOS','BELEZA_E_CUIDADOS_PESSOAIS','CASA_E_COZINHA','ESPORTES_E_LAZER','LIVROS','BRINQUEDOS_E_JOGOS','FERRAMENTAS_E_JARDIM','AUTOMOTIVO','INFORMATICA','SAUDE_E_BEM_ESTAR','MOVEIS','DECORACAO','PETS','VIAGEM','JARDINAGEM','ARTIGOS_DE_FESTA','INSTRUMENTOS_MUSICAIS','ARTESANATO')),
        description varchar(255),
        img_url varchar(255),
        name varchar(255),
        sku varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table shopping_cart (
        price_total_final numeric(38,2),
        price_total_items numeric(38,2),
        shipping numeric(38,2),
        taxes numeric(38,2),
        created_at timestamp(6),
        discount_id bigint,
        id bigint generated by default as identity,
        payment_method bigint,
        updated_at timestamp(6),
        user_id bigint unique,
        status varchar(255) check (status in ('ACTIVE','COMPLETED','CANCELED','PENDING_PAYMENT','SHIPPED','DELIVERED')),
        primary key (id)
    );

    create table users (
        email_verified boolean,
        is_active boolean,
        create_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_login timestamp(6),
        role_id bigint not null,
        shopping_cart_id bigint unique,
        update_at timestamp(6) not null,
        phone_number varchar(11),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password varchar(255) not null,
        reset_password_token varchar(255),
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists address 
       add constraint FK6i66ijb8twgcqtetl8eeeed6v 
       foreign key (user_id) 
       references users;

    alter table if exists cart_item 
       add constraint FKqkqmvkmbtiaqn2nfqf25ymfs2 
       foreign key (product_id) 
       references products;

    alter table if exists cart_item 
       add constraint FKe89gjdx91fxnmkkssyoim8xfu 
       foreign key (shopping_cart_id) 
       references shopping_cart;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FKsxfvku34v9ujavmj9ao69vo8s 
       foreign key (discount_id) 
       references discounts;

    alter table if exists orders 
       add constraint FK4q9i5ocee718mqyc415foi9ct 
       foreign key (payment_method) 
       references payment_methods;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists shopping_cart 
       add constraint FKdu1q2dc4vr5xbht7qxkaxdxsq 
       foreign key (discount_id) 
       references discounts;

    alter table if exists shopping_cart 
       add constraint FK5v7hqn19tbj0k6li11onu50na 
       foreign key (payment_method) 
       references payment_methods;

    alter table if exists shopping_cart 
       add constraint FKr1irjigmqcpfrvggavnr7vjyv 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    alter table if exists users 
       add constraint FKg9bdq6h4q87ner8a59wsiq39d 
       foreign key (shopping_cart_id) 
       references shopping_cart;

    create table address (
        is_primary boolean,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint,
        city varchar(255),
        complement varchar(255),
        country varchar(255),
        house_number varchar(255),
        neighborhood varchar(255),
        postal_code varchar(255),
        state varchar(255),
        street varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table cart_item (
        price numeric(38,2),
        quantity integer,
        id bigint generated by default as identity,
        product_id bigint,
        shopping_cart_id bigint,
        primary key (id)
    );

    create table discounts (
        discount_amount numeric(38,2),
        id bigint generated by default as identity,
        discount_code varchar(255),
        primary key (id)
    );

    create table order_items (
        price_at_purchase numeric(38,2),
        quantity integer,
        id bigint generated by default as identity,
        order_id bigint not null,
        product_id bigint not null,
        product_name varchar(255),
        primary key (id)
    );

    create table orders (
        freight_price numeric(38,2),
        price_total numeric(38,2) not null,
        taxes numeric(38,2),
        created_at timestamp(6),
        date_of_receipt timestamp(6),
        delivery_date timestamp(6),
        discount_id bigint,
        dispatch_date timestamp(6),
        id bigint generated by default as identity,
        payment_method bigint,
        return_deadline timestamp(6),
        user_id bigint,
        status varchar(255) check (status in ('IN_PREPARATION','CANCELED','PENDING_PAYMENT','DELIVERED')),
        tracking_code varchar(255) unique,
        primary key (id)
    );

    create table payment_methods (
        id bigint generated by default as identity,
        method varchar(255) not null unique,
        primary key (id)
    );

    create table products (
        dimensions float(53) not null,
        price numeric(38,2),
        sales_count integer,
        stock integer not null,
        weight float(53) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        brand varchar(255),
        category varchar(255) check (category in ('ALIMENTOS_E_BEBIDAS','MODA','ELETRONICOS','BELEZA_E_CUIDADOS_PESSOAIS','CASA_E_COZINHA','ESPORTES_E_LAZER','LIVROS','BRINQUEDOS_E_JOGOS','FERRAMENTAS_E_JARDIM','AUTOMOTIVO','INFORMATICA','SAUDE_E_BEM_ESTAR','MOVEIS','DECORACAO','PETS','VIAGEM','JARDINAGEM','ARTIGOS_DE_FESTA','INSTRUMENTOS_MUSICAIS','ARTESANATO')),
        description varchar(255),
        img_url varchar(255),
        name varchar(255),
        sku varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table shopping_cart (
        price_total_final numeric(38,2),
        price_total_items numeric(38,2),
        shipping numeric(38,2),
        taxes numeric(38,2),
        created_at timestamp(6),
        discount_id bigint,
        id bigint generated by default as identity,
        payment_method bigint,
        updated_at timestamp(6),
        user_id bigint unique,
        status varchar(255) check (status in ('ACTIVE','COMPLETED','CANCELED','PENDING_PAYMENT','SHIPPED','DELIVERED')),
        primary key (id)
    );

    create table users (
        email_verified boolean,
        is_active boolean,
        create_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_login timestamp(6),
        role_id bigint not null,
        shopping_cart_id bigint unique,
        update_at timestamp(6) not null,
        phone_number varchar(11),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password varchar(255) not null,
        reset_password_token varchar(255),
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists address 
       add constraint FK6i66ijb8twgcqtetl8eeeed6v 
       foreign key (user_id) 
       references users;

    alter table if exists cart_item 
       add constraint FKqkqmvkmbtiaqn2nfqf25ymfs2 
       foreign key (product_id) 
       references products;

    alter table if exists cart_item 
       add constraint FKe89gjdx91fxnmkkssyoim8xfu 
       foreign key (shopping_cart_id) 
       references shopping_cart;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FKsxfvku34v9ujavmj9ao69vo8s 
       foreign key (discount_id) 
       references discounts;

    alter table if exists orders 
       add constraint FK4q9i5ocee718mqyc415foi9ct 
       foreign key (payment_method) 
       references payment_methods;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists shopping_cart 
       add constraint FKdu1q2dc4vr5xbht7qxkaxdxsq 
       foreign key (discount_id) 
       references discounts;

    alter table if exists shopping_cart 
       add constraint FK5v7hqn19tbj0k6li11onu50na 
       foreign key (payment_method) 
       references payment_methods;

    alter table if exists shopping_cart 
       add constraint FKr1irjigmqcpfrvggavnr7vjyv 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    alter table if exists users 
       add constraint FKg9bdq6h4q87ner8a59wsiq39d 
       foreign key (shopping_cart_id) 
       references shopping_cart;
